### PR TITLE
fix: props error when opening devtools, close #59

### LINKED ISSUE #59: not working together with vue dev tools
Hello
It seems not working together with vue dev tools. 
``` javascript
import Vue from 'vue';
import Test from './Test';
import vgl from 'vue-golden-layout'
Vue.use(vgl);
new Vue({
    render: h => h(Test),
}).$mount('#test');
```
``` html
<template>
    <div>
        <golden-layout>
            <gl-row>
                <gl-stack>
                    <gl-component :title="'Test'">
                        <h2>Test</h2>
                    </gl-component>
                </gl-stack>
            </gl-row>
        </golden-layout>
    </div>
</template>
<script>
    export default {
        name: "Test"
    }
</script>
```
When the page is loaded, after visit dev tools, then each event of golden layout (e.g drag) will give this:
backend-no-props
Then it exists until the browser reopen. 
How to make it work with dev-tools?

### PR DESCRIPTION
**Pull request by NeverBehave**

### CODE REVIEW

**Comment by NeverBehave** [comment]
Wondering if this solution okey here? 
I have used this workaround for a while and looks like there is no side effect appears.

**Comment by eddow** [comment]
Sorry, I just saw the PR now.
Indeed, to have `__ob__` is going to do the job as well as having `_isVue = true` and the way to find back `Observer` was quick ingenious.
Thanks!

**Comment by NeverBehave** [comment]
Is it possible to build a release for this fix on npm? thanks

**Comment by eddow** [comment]
Sure, done

**Pull request merged**
