### PR TITLE
updated the depends within package.json, added jquery as a depend for…

### PR DESCRIPTION
**Pull request by grbd**
Hi,
I've made some updates

  * updates to packages within package.json
  * added jquery to depends for when setting up the demo using pnpm instead of npm
  * minor fix to the code as part of the depends update

### CODE REVIEW

**Comment by eddow** [comment]
I guess you checked the demo app is not broken ?
note: I will not upgrade yet on npm as I have another bug to solve and gather them in one update

**Comment by grbd** [comment]
It seems to work okay under Chrome, but broken under Firefox
that being said the original version seems to be the same way as well, so I suspect that's not due to a npm update

I've noticed there's been some more npm package updates recently on top of those I've done in this pull request, if I try applying those then it breaks under both browsers

**Comment by grbd** [comment]
I'm getting random results even with the original source so I'm going to close this for now

**Comment by eddow** [comment]
Oh, ok - thanks, I was still trying to reproduce

**Comment by eddow** [comment]
Ahh - sorry, I got confused as I didn't you you had 2 concurrent PR

**Pull request closed without merging**
